theme: minima
title: Hayley's Blog
author: Hye Ryung Son (hyeryung.son@snu.ac.kr)
description: This is a compilation of notes taken for self-study & polished articles to present NLP, AI, mental health related contents to public.
